stages:
  - lint
  - test
  - build

lint:
  image: golang:1.15.0-alpine3.12
  stage: lint
  before_script:
    # - apk -U add bash git gcc musl-dev docker vim less file curl wget ca-certificates
    # - git -C /go/src/golang.org/x/lint/golint checkout -b current 06c8688daad7faa9da5a0c2f163a3d14aac986ca
    # - go install golang.org/x/lint/golint
    # - rm -rf /go/src /go/pkg
    # - mkdir -p /go/src/golang.org/x
    # - cd /go/src/golang.org/x
    # - git clone https://github.com/golang/tools
    # - git -C /go/src/golang.org/x/tools checkout -b current aa82965741a9fecd12b026fbb3d3c6ed3231b8f8
    # - go install golang.org/x/tools/cmd/goimports
    # - cd -
    # - rm -rf /go/src /go/pkg
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.30.0
    - install ./bin/golangci-lint /bin/golangci-lint
    - rm -f ./bin/golangci-lint
  script:
    - golangci-lint run
