stages:
  - lint
  - test
  - build
  - release

lint:
  image: golang:1.15.0-alpine3.12
  stage: lint
  before_script:
    - apk add --no-cache bash git gcc musl-dev file curl wget ca-certificates
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.30.0
    - install ./bin/golangci-lint /bin/golangci-lint
    - rm -f ./bin/golangci-lint
  script:
    - golangci-lint run -v

build:bin:
  image: golang:1.15.0-alpine3.12
  stage: build
  before_script:
    - apk add --no-cache bash git gcc musl-dev file curl wget ca-certificates
  script:
    -  make build
  artifacts:
    paths:
      - build/deliver

.container:
  image: docker:stable
  stage: build
  services:
    - docker:stable-dind
  before_script:
    - apk add --no-cache make
    - echo ${DOCKER_PASSWORD:-$CI_REGISTRY_PASSWORD}|docker login -u=${DOCKER_USER:-$CI_REGISTRY_USER} --password-stdin ${DOCKER_REGISTRY:-$CI_REGISTRY}
  script:
    - make build-docker
    - make push-docker
  after_script:
    - docker logout

# build container image and upload it to gitlab registry
build:docker:
  extends: .container
  except:
    - tags

# build container image and upload it to docker hub
release:docker:
  extends: .container
  stage: release
  variables:
    DOCKER_REGISTRY: docker.io
  only:
    - tags
